# Generated by Django 2.0.5 on 2018-06-17 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CertificateWeb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=30)),
                ('file', models.FileField(upload_to='CertificateWeb/static/keys')),
            ],
        ),
    ]
