# Generated by Django 2.0.5 on 2018-06-18 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CertificateWeb', '0002_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='CerApply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('locality', models.CharField(max_length=100)),
                ('organization', models.CharField(max_length=100)),
                ('common', models.CharField(max_length=100)),
                ('dsn', models.CharField(max_length=100)),
                ('authority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CertificateWeb.Authority')),
            ],
        ),
    ]
