# Generated by Django 2.0.5 on 2018-06-18 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CertificateWeb', '0004_certificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyForRevok',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('serialNumber', models.CharField(max_length=400)),
                ('authority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CertificateWeb.Authority')),
            ],
        ),
    ]
